name: Lint code

on: push

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install
        run: pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm lint
